### ISSUE TITLE
Can't build on 64bit Raspbian.

### ISSUE THREAD

**Issue by malcsmith** [tronyx/Docker-Nagios#13] opened 2022-02-14 17:40 UTC
**Describe the issue/bug**
Building docker container on

Linux pi-docker-2 5.10.63-v8+ #1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021 aarch64 GNU/Linux

Arch - aarch64

During make of  git clone https://github.com/NagiosEnterprises/nsca.git

I get UNAME_MACHINE = aarch64
UNAME_RELEASE = 5.10.63-v8+
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021
configure: error: cannot guess build type; you must specify one

**To Reproduce**
run docker build .

**Expected behavior**
Successful build.

**Actual behavior**
Build fails.

More context

Is it an out of date ./configure-guess?

Cloning into 'nsca'...
HEAD is now at 824f4ea Merge pull request #40 from NagiosEnterprises/maint
checking for a BSD-compatible install... /usr/bin/install -c
checking build system type... ./config.guess: unable to guess system type

This script, last modified 2006-12-08, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
and
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2006-12-08

uname -m = aarch64
uname -r = 5.10.63-v8+
uname -s = Linux
uname -v = #1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021

/usr/bin/uname -p = aarch64
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = aarch64
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = aarch64
UNAME_RELEASE = 5.10.63-v8+
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021
configure: error: cannot guess build type; you must specify one

**Comment by tronyx** [comment] 2022-02-14 19:42
It's possible it is due to the out of date config.guess, but it pulls from the official GitHub repo so they would need to correct this upstream.

**Comment by run2000** [comment] 2022-02-16 08:24
Yup, I got caught by this one recently.

The Ubuntu packaging of `automake` brings in newer versions of `config.guess` and `config.sub` as a dependency into /usr/share/misc.

You can copy these in to the NSCA source and it builds happily.

Lines 180-183 then look like

```
    git clone https://github.com/NagiosEnterprises/nsca.git && \
    cd nsca                                                 && \
    git checkout $NSCA_TAG                                  && \
    cp /usr/share/misc/config.* .                           && \
    ./configure                                                \
    ....
```

I went down a rabbit warren via https://github.com/nzbget/nzbget/issues/418 to figure this all out.

Hope that helps.

**Comment by tronyx** [comment] 2022-03-16 13:34
> Yup, I got caught by this one recently.
> 
> The Ubuntu packaging of `automake` brings in newer versions of `config.guess` and `config.sub` as a dependency into /usr/share/misc.
> 
> You can copy these in to the NSCA source and it builds happily.
> 
> Lines 180-183 then look like
> 
> ```
>     git clone https://github.com/NagiosEnterprises/nsca.git && \
>     cd nsca                                                 && \
>     git checkout $NSCA_TAG                                  && \
>     cp /usr/share/misc/config.* .                           && \
>     ./configure                                                \
>     ....
> ```
> 
> I went down a rabbit warren via [nzbget/nzbget#418](https://github.com/nzbget/nzbget/issues/418) to figure this all out.
> 
> Hope that helps.

Are you aware whether or not this would have any negative impact on other Systems? I would like to make this change so that it doesn't require anyone to build their own image, but don't want it to break for others.

**Comment by tronyx** [comment] 2022-03-16 13:46
@malcsmith @run2000  - Just pushed the fix to the `develop` tag. Please try it and let me know if it works for you. It seems to work fine on my Ubuntu VM.

**Comment by run2000** [comment] 2022-03-21 05:15
On ARM64 it gets past that step, but fails with the additional plugins:

```
Building wheels for collected packages: pymssql
  Building wheel for pymssql (PEP 517): started
  Building wheel for pymssql (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpzov7ua
       cwd: /tmp/pip-install-xHOCc9/pymssql
  Complete output (21 lines):
  setup.py: platform.system() => 'Linux'
  setup.py: platform.architecture() => ('64bit', '')
  setup.py: platform.libc_ver() => ('glibc', '2.29')
  setup.py: Not using bundled FreeTDS
  setup.py: include_dirs = ['/usr/local/include']
  setup.py: library_dirs = ['/usr/local/lib']
  running bdist_wheel
  running build
  running build_ext
  cythoning src/_mssql.pyx to src/_mssql.c
  cythoning src/pymssql.pyx to src/pymssql.c
  building '_mssql' extension
  creating build
  creating build/temp.linux-aarch64-2.7
  creating build/temp.linux-aarch64-2.7/src
  aarch64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Mlh1FU/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/include -I/usr/include/python2.7 -c src/_mssql.c -o build/temp.linux-aarch64-2.7/src/_mssql.o -DMSDBLIB
  src/_mssql.c:6:10: fatal error: Python.h: No such file or directory
      6 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pymssql
Failed to build pymssql
ERROR: Could not build wheels for pymssql which use PEP 517 and cannot be installed directly
The command '/bin/sh -c cd /opt &&     wget -q -O get-pip.py https://bootstrap.pypa.io/pip/2.7/get-pip.py &&     python2 get-pip.py &&     pip install --no-cache-dir "pymssql<2.2.0" &&     pip3 install --no-cache-dir pywbem &&     git clone https://github.com/willixix/naglio-plugins.git WL-Nagios-Plugins &&     git clone https://github.com/JasonRivers/nagios-plugins.git JR-Nagios-Plugins &&     git clone https://github.com/justintime/nagios-plugins.git JE-Nagios-Plugins &&     git clone https://github.com/nagiosenterprises/check_mssql_collection.git nagios-mssql &&     wget -q -O ${NAGIOS_HOME}/libexec/check_ncpa.py https://raw.githubusercontent.com/NagiosEnterprises/ncpa/v2.0.5/client/check_ncpa.py &&     chmod +x /opt/WL-Nagios-Plugins/check* &&     chmod +x /opt/JE-Nagios-Plugins/check_mem/check_mem.pl &&     chmod +x ${NAGIOS_HOME}/libexec/check_ncpa.py &&     cp /opt/JE-Nagios-Plugins/check_mem/check_mem.pl ${NAGIOS_HOME}/libexec/ &&     cp /opt/nagios-mssql/check_mssql_database.py ${NAGIOS_HOME}/libexec/ &&     cp /opt/nagios-mssql/check_mssql_server.py ${NAGIOS_HOME}/libexec/' returned a non-zero code: 1

```
Likely this is unrelated to the change above.

**Comment by jkoan** [comment] 2022-03-21 05:28
> On ARM64 it gets past that step, but fails with the additional plugins:
> 
> ```
> Building wheels for collected packages: pymssql
>   Building wheel for pymssql (PEP 517): started
>   Building wheel for pymssql (PEP 517): finished with status 'error'
>   ERROR: Command errored out with exit status 1:
>    command: /usr/bin/python2 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpzov7ua
>        cwd: /tmp/pip-install-xHOCc9/pymssql
>   Complete output (21 lines):
>   setup.py: platform.system() => 'Linux'
>   setup.py: platform.architecture() => ('64bit', '')
>   setup.py: platform.libc_ver() => ('glibc', '2.29')
>   setup.py: Not using bundled FreeTDS
>   setup.py: include_dirs = ['/usr/local/include']
>   setup.py: library_dirs = ['/usr/local/lib']
>   running bdist_wheel
>   running build
>   running build_ext
>   cythoning src/_mssql.pyx to src/_mssql.c
>   cythoning src/pymssql.pyx to src/pymssql.c
>   building '_mssql' extension
>   creating build
>   creating build/temp.linux-aarch64-2.7
>   creating build/temp.linux-aarch64-2.7/src
>   aarch64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Mlh1FU/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/include -I/usr/include/python2.7 -c src/_mssql.c -o build/temp.linux-aarch64-2.7/src/_mssql.o -DMSDBLIB
>   src/_mssql.c:6:10: fatal error: Python.h: No such file or directory
>       6 | #include "Python.h"
>         |          ^~~~~~~~~~
>   compilation terminated.
>   error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
>   ----------------------------------------
>   ERROR: Failed building wheel for pymssql
> Failed to build pymssql
> ERROR: Could not build wheels for pymssql which use PEP 517 and cannot be installed directly
> The command '/bin/sh -c cd /opt &&     wget -q -O get-pip.py https://bootstrap.pypa.io/pip/2.7/get-pip.py &&     python2 get-pip.py &&     pip install --no-cache-dir "pymssql<2.2.0" &&     pip3 install --no-cache-dir pywbem &&     git clone https://github.com/willixix/naglio-plugins.git WL-Nagios-Plugins &&     git clone https://github.com/JasonRivers/nagios-plugins.git JR-Nagios-Plugins &&     git clone https://github.com/justintime/nagios-plugins.git JE-Nagios-Plugins &&     git clone https://github.com/nagiosenterprises/check_mssql_collection.git nagios-mssql &&     wget -q -O ${NAGIOS_HOME}/libexec/check_ncpa.py https://raw.githubusercontent.com/NagiosEnterprises/ncpa/v2.0.5/client/check_ncpa.py &&     chmod +x /opt/WL-Nagios-Plugins/check* &&     chmod +x /opt/JE-Nagios-Plugins/check_mem/check_mem.pl &&     chmod +x ${NAGIOS_HOME}/libexec/check_ncpa.py &&     cp /opt/JE-Nagios-Plugins/check_mem/check_mem.pl ${NAGIOS_HOME}/libexec/ &&     cp /opt/nagios-mssql/check_mssql_database.py ${NAGIOS_HOME}/libexec/ &&     cp /opt/nagios-mssql/check_mssql_server.py ${NAGIOS_HOME}/libexec/' returned a non-zero code: 1
> ```
> 
> Likely this is unrelated to the change above.

I had the same issue when building for arm which I fixed here: c4fb3ae2e3556541ed511f75ca1154d73980b262

Currently I am working on #15 Which is the branch here: https://github.com/jkoan/Docker-Nagios/commits/docker-build

With my branch it's already working well.

**Comment by tronyx** [comment] 2022-03-21 14:47
> On ARM64 it gets past that step, but fails with the additional plugins:
> 
> ```
> Building wheels for collected packages: pymssql
>   Building wheel for pymssql (PEP 517): started
>   Building wheel for pymssql (PEP 517): finished with status 'error'
>   ERROR: Command errored out with exit status 1:
>    command: /usr/bin/python2 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpzov7ua
>        cwd: /tmp/pip-install-xHOCc9/pymssql
>   Complete output (21 lines):
>   setup.py: platform.system() => 'Linux'
>   setup.py: platform.architecture() => ('64bit', '')
>   setup.py: platform.libc_ver() => ('glibc', '2.29')
>   setup.py: Not using bundled FreeTDS
>   setup.py: include_dirs = ['/usr/local/include']
>   setup.py: library_dirs = ['/usr/local/lib']
>   running bdist_wheel
>   running build
>   running build_ext
>   cythoning src/_mssql.pyx to src/_mssql.c
>   cythoning src/pymssql.pyx to src/pymssql.c
>   building '_mssql' extension
>   creating build
>   creating build/temp.linux-aarch64-2.7
>   creating build/temp.linux-aarch64-2.7/src
>   aarch64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Mlh1FU/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/include -I/usr/include/python2.7 -c src/_mssql.c -o build/temp.linux-aarch64-2.7/src/_mssql.o -DMSDBLIB
>   src/_mssql.c:6:10: fatal error: Python.h: No such file or directory
>       6 | #include "Python.h"
>         |          ^~~~~~~~~~
>   compilation terminated.
>   error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
>   ----------------------------------------
>   ERROR: Failed building wheel for pymssql
> Failed to build pymssql
> ERROR: Could not build wheels for pymssql which use PEP 517 and cannot be installed directly
> The command '/bin/sh -c cd /opt &&     wget -q -O get-pip.py https://bootstrap.pypa.io/pip/2.7/get-pip.py &&     python2 get-pip.py &&     pip install --no-cache-dir "pymssql<2.2.0" &&     pip3 install --no-cache-dir pywbem &&     git clone https://github.com/willixix/naglio-plugins.git WL-Nagios-Plugins &&     git clone https://github.com/JasonRivers/nagios-plugins.git JR-Nagios-Plugins &&     git clone https://github.com/justintime/nagios-plugins.git JE-Nagios-Plugins &&     git clone https://github.com/nagiosenterprises/check_mssql_collection.git nagios-mssql &&     wget -q -O ${NAGIOS_HOME}/libexec/check_ncpa.py https://raw.githubusercontent.com/NagiosEnterprises/ncpa/v2.0.5/client/check_ncpa.py &&     chmod +x /opt/WL-Nagios-Plugins/check* &&     chmod +x /opt/JE-Nagios-Plugins/check_mem/check_mem.pl &&     chmod +x ${NAGIOS_HOME}/libexec/check_ncpa.py &&     cp /opt/JE-Nagios-Plugins/check_mem/check_mem.pl ${NAGIOS_HOME}/libexec/ &&     cp /opt/nagios-mssql/check_mssql_database.py ${NAGIOS_HOME}/libexec/ &&     cp /opt/nagios-mssql/check_mssql_server.py ${NAGIOS_HOME}/libexec/' returned a non-zero code: 1
> ```
> 
> Likely this is unrelated to the change above.

Does it just not run on ARM64 as-is without trying to build it?

**Comment by jkoan** [comment] 2022-03-21 14:50
Actually no. Probably on pypi thers no package prebuild?

**Comment by tronyx** [comment] 2022-03-21 15:18
> Actually no. Probably on pypi thers no package prebuild?

So the existing image does or does not work? I would assume there's no package pre-build given the error. Would have to do some research on it though.

**Comment by jkoan** [comment] 2022-03-21 17:27
Here you can see binary packages for i686 and x86_64 for everything else the package will be built on installation https://pypi.org/project/pymssql/#files 

As a alternative we could use the Debian packages. I can look into this

**Comment by tronyx** [comment] 2023-02-27 13:08
I got multi-branch multi-architecture matrix builds working so there is now an `amd64`, `arm64`, and `arm-v7` architecture variation of this image.

https://sharex.tronflix.app/zORI8/LALEJEPo06.png/raw

@malcsmith & @jkoan - Please test this with the `:develop` branch and let me know.

**Comment by jkoan** [comment] 2023-02-27 13:18
> I got multi-branch multi-architecture matrix builds working so there is now an `amd64`, `arm64`, and `arm-v7` architecture variation of this image.
> 
> https://sharex.tronflix.app/zORI8/LALEJEPo06.png/raw
> 
> @malcsmith & @jkoan - Please test this with the `:develop` branch and let me know.

Works on armv7

**Comment by tronyx** [comment] 2023-02-27 23:14
Confirmed it is working on `arm64` so I am closing this and will be merging to `master` soon.

**Closed as completed by tronyx** 2023-02-27 23:14 UTC
Labels: bug
